# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

batch_size: 1  # batch_size

dataset: lit-pcba  # dataset: lit-pcba or muv
num_workers: 4  # number of workers
data_fpath: /mnt/docking/dud-e.smina.serialized  # file path of the datasets
# valid_split_ratio: 0.3
data_keys: keys/lit-pcba.pkl

local_rank: null  # Rank of current process
local_world_size: null  # World size (used by the launch script)
model: ???  # model name

load_from: ???  # path to checkpoint
output_path: ???  # path to save the result CSV file
